name: zoo_connect_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  audioplayers: ^6.5.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^2.6.1
  flutter_survey: ^1.0.1
  freezed_annotation: ^3.1.0
  html_unescape: ^2.0.0
  http: ^1.5.0
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.2.2
  build_runner: ^2.5.4
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/sounds/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/background.png" 
  adaptive_icon_foreground: "assets/icon/icon.png" 
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/icon/icon.png"